service: attributy-task-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  timeout: 150

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /api/posts
      - http:
          method: ANY
          path: /api/posts/{any+}

plugins:
  - serverless-offline

custom:
  dotenv:
    basePath: ./

org: null
app: null
