service: attributy-task-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  timeout: 150
  profile: serverless-framework
  environment:
    MONGO_URL: ${env:MONGO_URL}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /api/posts
          cors: true
      - http:
          method: ANY
          path: /api/posts/{any+}
          cors: true
      - http:
          method: ANY
          path: /api/users
          cors: true
      - http:
          method: ANY
          path: /api/users/{any+}
          cors: true
      - http:
          method: ANY
          path: /api/auth
          cors: true
      - http:
          method: ANY
          path: /api/auth/{any+}
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    basePath: ./
